#连接设置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ets?severTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: root
    tomcat:
      max-active: 50
      initial-size: 10
      max-idle: 20
      min-idle: 5
      max-wait: 60000
logging:
  level:
    com.ets: debug
server:
  port: 8111
